### ISSUE TITLE
Color output results in garbage on Windows

### ISSUE THREAD

**Issue by rudylattae** [alfredodeza/konira#10]
The color codes used in the output of test results are not compatible with the DOS shell on Windows.

```
foo
←[91m    It should return foo←[0m

nothing really
←[92m    It should be true←[0m

←[91mFailures:
---------←[0m
←[91m
1 ==> AssertionError←[0m
←[91mStarts and Ends: ←[0m←[1mC:\...py:12:←[0m


←[91m1 spec failed, 2 total in 0.026 secs.
←[0m
```

This makes it rather difficult to read the output of the test results hence renders konira unusable on Windows at the moment.

Would you consider a possible refactor of the `output` module to allow turning off colored output? A command line option could be passed to flag color output off:

```
$ konira -no-color
```

Or somthing like that.

Alternatively you could incorporate a crossplatform terminal coloring shim like http://pypi.python.org/pypi/colorama to help those poor Winblows devs out. What say you?

**Comment by alfredodeza** [comment]
This is an easy fix and should be in the next minor Konira release. There will be no need for a command line flag, it will just detect if the environment is Windows and will not output colored text if this is the case.

As a temporary workaround, you could install `pytest-konira` that allows you to use `py.test` as the test runner for konira test cases.

**Comment by alfredodeza** [comment]
A branch has been created to track and fix this issue: `ms-support`.

There is a commit that implements a fix for this, please checkout this branch and confirm this solves _this_ issue:

https://github.com/alfredodeza/konira/commit/ab0224f463242b5578d1de9a73082a669daa50d7

**Comment by rudylattae** [comment]
I tested it on Windows 7, it works great! That check for `sys.platform == 'win32'` would definitely match XP and Vista as well. I say this is good to go.

**Comment by alfredodeza** [comment]
I am closing this issue as this feature is already in ms-support and soon to be merged into master
