### ISSUE TITLE
using cover option checks coverage of the konira package.

### ISSUE THREAD

**Issue by nathantoddstone** [alfredodeza/konira#14]
coverage is being run on package files in /dist-packages/konira/*.

not sure if i'm using it wrong, but this is not the desired behavior...

http://pastebin.com/n0us4YzP

**Comment by alfredodeza** [comment]
I think this all stems from non-specific documentation (http://konira.cafepais.com/docs/commandline.html#coverage) where I am not emphasizing that by default the coverage command will act just like running coverage on the command line, which is: it will track everything your code is touching.

Your output looks like what _I_ would expect, since no argument was passed to `cover` then the output included everything that your code touched when it run (including konira).

If for example, you imported `os` and used it somehow, you would see those results there as well.

At the end of your output, you have the coverage for your single test called `foo` in a directory called test. I am not sure if you are testing a module or trying out konira with a temporary directory.

If it is a temporary directory then you are looking to have a command like this (using the information from your pastebin)::

```
``konira cover .``
```

or also::

```
``konira cover test``
```

In the case you were developing a module, you could pass in the name of the module::

```
``konira cover my_module_name``
```

And if it is a specific part of the module, you would do it like this::

```
``konira cover my_module_name.some_sub_module``
```

Let me know if any of the above solves your problem so I can close this issue.

**Comment by nathantoddstone** [comment]
i'm running konira from the root of a module, the tested files are in subpackages. 
`konira cover foo`
does only show coverage results for foo.py
but passing . or a package name still get the konira package covered.
also, using
`konira cover --show-missing foo`
covers the konira package again.

i suppose this is really a problem with coverage, and not with konira. i'm happy with using.
`konira cover foo`
thanks...

**Comment by alfredodeza** [comment]
hrmnnn `--show-missing` does not take an argument.

**Comment by nathantoddstone** [comment]
maybe using the pytest runner i can circumvent some of these issues with coverage... so you can focus on konira and not integration with other people packages... :)

**Comment by alfredodeza** [comment]
True. But to me this sounds like we are both half there. I think it works as expected but you are finding a corner case.

Either way, I am still interested in fixing it. I have not been able to replicate so any help with code, file structure etc... that would be great.

This should just _work_.

Trying out py.test and pytest-konira would be helpful to see what the outcome is.

**Comment by nathantoddstone** [comment]
on a fresh install of ubuntu 11.04 on vmware fusion.
install python-dev, python-pip, konira, coverage.
make /module/package/...
in /package, make **init**.py, foo.py and case_foo.py, using your example test from docs.
in terminal: cd /module, konira cover. results in covering the konira package and foo.py.

**Comment by alfredodeza** [comment]
This is what I did to replicate and was not able to get what you describe:

http://paste.pocoo.org/show/498389/

Can you confirm I followed your steps correctly?

**Comment by nathantoddstone** [comment]
yeah, thats exactly what i've done. weird. must just be a corner case. did you try it in an ubuntu vm? that was my test space.

**Comment by alfredodeza** [comment]
I have not tried in Ubuntu. What steps are you using before creating the directory? Are you in a virtualenv? how did you installed Konira?

**Comment by nathantoddstone** [comment]
not using virtualenv, but i tried it in a fresh vm install of ubuntu
to insulate from other factors. konira was pip installed. maybe its an
issue with python on ubuntu...

On Thu, Oct 27, 2011 at 7:39 AM, Alfredo Deza
reply@reply.github.com
wrote:

> I have not tried in Ubuntu. What steps are you using before creating the directory? Are you in a virtualenv? how did you installed Konira?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/alfredodeza/konira/issues/14#issuecomment-2544243

## 

nathan toddstone
www.nathantoddstone.com
nathan@nathantoddstone.com

**Comment by alfredodeza** [comment]
can you try uninstalling konira from the global Python environment and use virtualenv? I highly discourage using global installations

**Comment by nathantoddstone** [comment]
ok. just installed and figured out how to use virtualenv, and that
coverage issue stopped happening.

sorry for wasting your time.

good excuse to get going with virtualenv anyway, i guess :)

On Thu, Oct 27, 2011 at 9:17 AM, Alfredo Deza
reply@reply.github.com
wrote:

> can you try uninstalling konira from the global Python environment and use virtualenv? I highly discourage using global installations
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/alfredodeza/konira/issues/14#issuecomment-2545625

## 

nathan toddstone
www.nathantoddstone.com
nathan@nathantoddstone.com

**Comment by alfredodeza** [comment]
Hey Nathan, no worries. You are bringing to my attention something that I know but should emphasize in the docs: _always_ use a Virtualenv.

By no means you are wasting my time. Thanks for using Konira _and_ taking the time to report issues you have with it.

**Comment by nathantoddstone** [comment]
:)

On Thu, Oct 27, 2011 at 10:18 AM, Alfredo Deza
reply@reply.github.com
wrote:

> Hey Nathan, no worries. You are bringing to my attention something that I know but should emphasize in the docs: _always_ use a Virtualenv.
> 
> By no means you are wasting my time. Thanks for using Konira _and_ taking the time to report issues you have with it.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/alfredodeza/konira/issues/14#issuecomment-2546466

## 

nathan toddstone
www.nathantoddstone.com
nathan@nathantoddstone.com
