### ISSUE TITLE
Describe classes

### ISSUE THREAD

**Issue by lucassmagal** [alfredodeza/konira#17]
Hello,

Can I describe classes in konira like this:

describe Auth:
    it (...)

describe Auth, "when it's a new user":
    it (...)

**Comment by alfredodeza** [comment]
you cannot use describe that way, sorry.

Unless what you are looking for is inheritance? If you have a parent class called `Foo` then it would be something like:

```
describe "my test class", Foo:
    ...
```

**Comment by lucassmagal** [comment]
Don't be interesting do it this way? I'm really interested in implement this feature, if you agree with me.

**Comment by alfredodeza** [comment]
What would a feature like that give you? I don't see the potential usefulness of it. Could you please elaborate a bit more as to what is it that you want from it?

**Comment by lucassmagal** [comment]
I think it's useful to manage multiple contexts, like "subject" feature in rspec: http://benscheirman.com/2011/05/dry-up-your-rspec-files-with-subject-let-blocks

**Comment by posativ** [comment]
After all, konira is still python and this requires a huge (ruby)-parser for a single use case. Take a look at python's stdlib tokenize/ast and play around to see what's easy (and thus less error-prone) to implement and what's almost impossible.
