### ISSUE TITLE
Is the project still live?

### ISSUE THREAD

**Issue by hackrole** [alfredodeza/konira#25]
the doc site: http://konira.cafepais.com seems not exists now.
the example in the README is even not full enough to getting-konira-run.
I was very interesting in BDD, so waiting for your answer.

**Comment by alfredodeza** [comment]
This project is no longer maintained. Sorry. However, it should work for you, is there anything in particular that didn't work?

**Comment by daveshah** [comment]
@alfredodeza no longer maintained because of time / other issues?

**Comment by alfredodeza** [comment]
@daveshah I don't think there was ever much interested so I stopped adding features. Things should still work though.

**Comment by hackrole** [comment]
Indeed, the problem is I even donot know how to start to use this lib. the doc in the readme.md really confusing and not-completed.

**Comment by alfredodeza** [comment]
@hackrole let me bring up the website up again, I swear the docs are great :)

**Comment by alfredodeza** [comment]
@hackrole http://konira.cafepais.com/ should now be available (hopefully DNS has propagated already)
